version: "3.4"
networks:
   proxy:
    external:
     name: remoteproxy_proxy
   hostnet:
    external:
     name: host

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - target: 9000
        published: 9000
        mode: host
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - //opt/portainer:/data
    networks:
      -  remoteproxy_proxy
      - hostnet: {}
    deploy:
      placement:
        constraints:
        - node.role == manager
      replicas: 1
      update_config:
        parallelism: 1
        delay: 0s

  portainer-arm:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - target: 9000
        published: 9000
        mode: host
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - //opt/portainer:/data
    networks:
      -  remoteproxy_proxy
      - hostnet: {}
    deploy:
      placement:
        constraints:
          - node.role == manager
          - engine.labels.arch == amd64
      replicas: 1
      update_config:
        parallelism: 1
        delay: 0s
