version: "3.4"

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - target: 9000
        published: 9000
        mode: ingress
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - //opt/portainer:/data
      - /etc/localtime:/etc/localtime:ro
    deploy:
      placement:
        constraints:
        - node.role == manager
      replicas: 2
      labels:
      - traefik.port=9000
      update_config:
        parallelism: 1
        delay: 0s